
import React, { useState, useEffect } from 'react';
import { Card, CardContent } from '../ui/Card';
import Button from '../ui/Button';
import Spinner from '../ui/Spinner';
import { 
    fetchCoachingContent, addCoachingContent, updateCoachingContent, deleteCoachingContent,
    fetchExclusiveContent, addExclusiveContent, updateExclusiveContent, deleteExclusiveContent,
    fetchTeamYamVideos, addTeamYamVideo, updateTeamYamVideo, deleteTeamYamVideo,
    fetchArchiveData, addArchiveItem, updateArchiveItem, deleteArchiveItem,
    fetchBehindTheScenesData, addBehindTheScenesContent, updateBehindTheScenesContent, deleteBehindTheScenesContent
} from '../../services/api';
import PencilIcon from '../icons/PencilIcon';
import TrashIcon from '../icons/TrashIcon';
import PlusCircleIcon from '../icons/PlusCircleIcon';

type FeatureType = 'coaching' | 'exclusive' | 'team-yam' | 'archive' | 'behind-the-scenes';

const FeatureManagement: React.FC = () => {
    const [activeType, setActiveType] = useState<FeatureType>('coaching');
    const [items, setItems] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingItem, setEditingItem] = useState<any | null>(null);
    
    // Generic Form State
    const [formData, setFormData] = useState<any>({});

    useEffect(() => {
        loadData();
    }, [activeType]);

    const loadData = async () => {
        setLoading(true);
        let data = [];
        try {
            switch (activeType) {
                case 'coaching': data = await fetchCoachingContent(); break;
                case 'exclusive': data = await fetchExclusiveContent(); break;
                case 'team-yam': data = await fetchTeamYamVideos(); break;
                case 'archive': data = await fetchArchiveData(); break;
                case 'behind-the-scenes': data = await fetchBehindTheScenesData(); break;
            }
            setItems(data);
        } catch (error) {
            console.error("Failed to load data", error);
        } finally {
            setLoading(false);
        }
    };

    const handleEdit = (item: any) => {
        setEditingItem(item);
        setFormData(item); // Populate form with item data
        setIsModalOpen(true);
    };

    const handleAdd = () => {
        setEditingItem(null);
        setFormData({}); // Reset form
        setIsModalOpen(true);
    };

    const handleDelete = async (id: string) => {
        if (!window.confirm("Delete this item?")) return;
        try {
            switch (activeType) {
                case 'coaching': await deleteCoachingContent(id); break;
                case 'exclusive': await deleteExclusiveContent(id); break;
                case 'team-yam': await deleteTeamYamVideo(id); break;
                case 'archive': await deleteArchiveItem(id); break;
                case 'behind-the-scenes': await deleteBehindTheScenesContent(id); break;
            }
            loadData();
        } catch (error) {
            console.error("Delete failed", error);
        }
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            if (editingItem) {
                switch (activeType) {
                    case 'coaching': await updateCoachingContent(editingItem.id, formData); break;
                    case 'exclusive': await updateExclusiveContent(editingItem.id, formData); break;
                    case 'team-yam': await updateTeamYamVideo(editingItem.id, formData); break;
                    case 'archive': await updateArchiveItem(editingItem.id, formData); break;
                    case 'behind-the-scenes': await updateBehindTheScenesContent(editingItem.id, formData); break;
                }
            } else {
                // Add logic requires omitting ID which is usually generated by Firestore, but here simple passing is fine
                switch (activeType) {
                    case 'coaching': await addCoachingContent(formData); break;
                    case 'exclusive': await addExclusiveContent(formData); break;
                    case 'team-yam': await addTeamYamVideo({ ...formData, likes: 0, date: new Date().toISOString().split('T')[0] }); break;
                    case 'archive': await addArchiveItem(formData); break;
                    case 'behind-the-scenes': await addBehindTheScenesContent(formData); break;
                }
            }
            setIsModalOpen(false);
            loadData();
        } catch (error) {
            console.error("Save failed", error);
            alert("Failed to save item.");
        }
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData((prev: any) => ({ ...prev, [name]: value }));
    };
    
    const inputClass = "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm";


    const renderFormFields = () => {
        switch (activeType) {
            case 'coaching':
                return (
                    <>
                        <input name="title" value={formData.title || ''} onChange={handleInputChange} placeholder="Title" className={inputClass} required />
                        <select name="type" value={formData.type || 'Tactic'} onChange={handleInputChange} className={inputClass}>
                            <option>Tactic</option><option>Drill</option><option>Column</option><option>Video</option>
                        </select>
                        <textarea name="summary" value={formData.summary || ''} onChange={handleInputChange} placeholder="Summary" className={inputClass} required />
                        <input name="imageUrl" value={formData.imageUrl || ''} onChange={handleInputChange} placeholder="Image URL" className={inputClass} />
                        <input name="author" value={formData.author?.name || (typeof formData.author === 'string' ? formData.author : '')} onChange={(e) => setFormData({...formData, author: e.target.value})} placeholder="Author Name" className={inputClass} />
                    </>
                );
            case 'exclusive':
                return (
                    <>
                        <input name="title" value={formData.title || ''} onChange={handleInputChange} placeholder="Headline" className={inputClass} required />
                        <input name="author" value={formData.author || ''} onChange={handleInputChange} placeholder="Interviewee Name" className={inputClass} required />
                        <input name="role" value={formData.role || ''} onChange={handleInputChange} placeholder="Role (e.g. CEO)" className={inputClass} required />
                        <textarea name="summary" value={formData.summary || ''} onChange={handleInputChange} placeholder="Summary" className={inputClass} required />
                        <input name="imageUrl" value={formData.imageUrl || ''} onChange={handleInputChange} placeholder="Image URL" className={inputClass} />
                        <input name="date" type="date" value={formData.date || ''} onChange={handleInputChange} className={inputClass} required />
                    </>
                );
            case 'team-yam':
                return (
                    <>
                        <input name="title" value={formData.title || ''} onChange={handleInputChange} placeholder="Video Title" className={inputClass} required />
                        <input name="teamName" value={formData.teamName || ''} onChange={handleInputChange} placeholder="Team Name" className={inputClass} required />
                        <input name="uploadedBy" value={formData.uploadedBy || ''} onChange={handleInputChange} placeholder="Uploader Name" className={inputClass} required />
                        <textarea name="description" value={formData.description || ''} onChange={handleInputChange} placeholder="Description" className={inputClass} required />
                        <input name="videoUrl" value={formData.videoUrl || ''} onChange={handleInputChange} placeholder="Video URL" className={inputClass} required />
                        <input name="thumbnailUrl" value={formData.thumbnailUrl || ''} onChange={handleInputChange} placeholder="Thumbnail URL" className={inputClass} />
                    </>
                );
             case 'archive':
                return (
                    <>
                        <input name="title" value={formData.title || ''} onChange={handleInputChange} placeholder="Title" className={inputClass} required />
                        <input name="year" type="number" value={formData.year || ''} onChange={handleInputChange} placeholder="Year" className={inputClass} required />
                        <select name="type" value={formData.type || 'photo'} onChange={handleInputChange} className={inputClass}>
                            <option value="photo">Photo</option><option value="match">Match</option><option value="clip">Clip</option>
                        </select>
                        <textarea name="description" value={formData.description || ''} onChange={handleInputChange} placeholder="Description" className={inputClass} required />
                        {/* Simplified handling for 'details' complex object for demo brevity */}
                        <p className="text-xs text-gray-500">Note: Complex 'details' object editing is simplified here.</p>
                    </>
                );
            case 'behind-the-scenes':
                return (
                    <>
                        <input name="title" value={formData.title || ''} onChange={handleInputChange} placeholder="Title" className={inputClass} required />
                        <select name="type" value={formData.type || 'photo'} onChange={handleInputChange} className={inputClass}>
                            <option value="photo">Photo</option><option value="video">Video</option>
                        </select>
                        <textarea name="description" value={formData.description || ''} onChange={handleInputChange} placeholder="Description" className={inputClass} required />
                        <input name="thumbnailUrl" value={formData.thumbnailUrl || ''} onChange={handleInputChange} placeholder="Thumbnail URL" className={inputClass} required />
                        <input name="contentUrl" value={formData.contentUrl || ''} onChange={handleInputChange} placeholder="Content URL (Full Photo / Video)" className={inputClass} required />
                    </>
                );
        }
    };

    return (
        <Card className="shadow-lg animate-fade-in">
            <CardContent className="p-6">
                <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
                    <h3 className="text-2xl font-bold font-display">Content Management</h3>
                    <div className="flex gap-2 flex-wrap justify-center">
                        {(['coaching', 'exclusive', 'team-yam', 'archive', 'behind-the-scenes'] as FeatureType[]).map(type => (
                            <button 
                                key={type}
                                onClick={() => setActiveType(type)}
                                className={`px-3 py-1 text-sm rounded capitalize ${activeType === type ? 'bg-primary text-white' : 'bg-gray-100 text-gray-600'}`}
                            >
                                {type.replace(/-/g, ' ')}
                            </button>
                        ))}
                    </div>
                    <Button onClick={handleAdd} className="bg-green-600 text-white text-sm flex items-center gap-1"><PlusCircleIcon className="w-4 h-4"/> Add New</Button>
                </div>

                {loading ? <div className="flex justify-center py-8"><Spinner /></div> : (
                    <div className="space-y-2">
                        {items.map(item => (
                            <div key={item.id} className="p-3 bg-white border rounded flex justify-between items-center">
                                <div>
                                    <p className="font-bold text-sm">{item.title || item.name || 'Untitled'}</p>
                                    <p className="text-xs text-gray-500 truncate max-w-md">{item.summary || item.description}</p>
                                </div>
                                <div className="flex gap-2">
                                    <button onClick={() => handleEdit(item)} className="p-1 bg-blue-100 text-blue-600 rounded"><PencilIcon className="w-4 h-4"/></button>
                                    <button onClick={() => handleDelete(item.id)} className="p-1 bg-red-100 text-red-600 rounded"><TrashIcon className="w-4 h-4"/></button>
                                </div>
                            </div>
                        ))}
                        {items.length === 0 && <p className="text-center text-gray-500 py-8">No content found.</p>}
                    </div>
                )}
            </CardContent>

            {isModalOpen && (
                <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4">
                    <div className="bg-white w-full max-w-lg rounded-lg shadow-xl p-6">
                        <h3 className="text-xl font-bold mb-4">{editingItem ? 'Edit Item' : 'Add Item'}</h3>
                        <form onSubmit={handleSave} className="space-y-4">
                            {renderFormFields()}
                            <div className="flex justify-end gap-2 mt-4">
                                <Button type="button" onClick={() => setIsModalOpen(false)} className="bg-gray-200 text-gray-800">Cancel</Button>
                                <Button type="submit" className="bg-primary text-white">Save</Button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </Card>
    );
};

export default FeatureManagement;
